select * from CUSTOMER inner join ADDRESS
on CUSTOMER.ADDRESS_ID = ADDRESS.ADDRESS_ID;

select CUSTOMER.CUSTOMER_ID, CUSTOMER.LAST_NAME, CUSTOMER.LAST_NAME, ADDRESS.ADDRESS, ADDRESS.PHONE
from CUSTOMER inner join ADDRESS
on CUSTOMER.ADDRESS_ID = ADDRESS.ADDRESS_ID;

select C.CUSTOMER_ID, C.LAST_NAME, C.LAST_NAME, A.ADDRESS, A.PHONE
from CUSTOMER C inner join ADDRESS A
on C.ADDRESS_ID = A.ADDRESS_ID;

select * from LOCATIONS L inner join COUNTRIES C on C.COUNTRY_ID = L.COUNTRY_ID;
select C.COUNTRY_NAME, L.CITY from LOCATIONS L inner join COUNTRIES C on C.COUNTRY_ID = L.COUNTRY_ID;

-- inner join: returns only the matching records from the tables