-- get first-name, last_name and department_name for all employees

SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;

SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_NAME
FROM EMPLOYEES E JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_NAME
FROM EMPLOYEES E JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE E.DEPARTMENT_ID IS NULL;

-- BE CAREFUL THERE COULD BE E.DEPARTMENT_ID IS NOT NULL BUT D.DEPARTMENT_ID IS NULL !!!
-- F.EX EMPLOYEE HAS DEPARTMENT_ID BUT THERE IS NO CORRESPONDING DEPARTMENT
-- THEREFORE WHERE D.DEPARTMENT_ID IS NULL; CAN BE USED INSTEAD OF WHERE E.DEPARTMENT_ID IS NULL;

-- JOIN THREE TABLES
-- get first_name, last_name and department_name, city for all employees
SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_NAME, CITY
FROM EMPLOYEES E JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN LOCATIONS L
ON D.LOCATION_ID = L.LOCATION_ID;

-- JOIN FOUR TABLES
-- get first_name, last_name and department_name, city, country_name for all employees
SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_NAME, CITY, COUNTRY_NAME
FROM EMPLOYEES E JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN LOCATIONS L
ON D.LOCATION_ID = L.LOCATION_ID
JOIN COUNTRIES C
ON L.COUNTRY_ID = C.COUNTRY_ID;