select * from EMPLOYEES;

select * from DEPARTMENTS;

SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_NAME
FROM EMPLOYEES E JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

SELECT COUNT(*) FROM (SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_NAME
                      FROM EMPLOYEES E JOIN DEPARTMENTS D
                                            ON E.DEPARTMENT_ID = D.DEPARTMENT_ID);

-- LEFT OUTER JOIN WITH WHERE
SELECT CUSTOMER_ID, FIRST_NAME, LAST_NAME, ADDRESS, PHONE
FROM CUSTOMER LEFT OUTER JOIN ADDRESS
ON CUSTOMER.ADDRESS_ID = ADDRESS.ADDRESS_ID
WHERE ADDRESS.ADDRESS_ID IS NULL;

SELECT CUSTOMER_ID, FIRST_NAME, LAST_NAME, CUSTOMER.ADDRESS_ID, ADDRESS.ADDRESS_ID,
       ADDRESS, PHONE
FROM CUSTOMER LEFT OUTER JOIN ADDRESS
ON CUSTOMER.ADDRESS_ID = ADDRESS.ADDRESS_ID
WHERE ADDRESS.ADDRESS_ID IS NULL;

-- FULL OUTER JOIN WITH WHERE
SELECT * FROM CUSTOMER FULL OUTER JOIN ADDRESS
ON CUSTOMER.ADDRESS_ID = ADDRESS.ADDRESS_ID
WHERE CUSTOMER.ADDRESS_ID IS NULL OR ADDRESS.ADDRESS_ID IS NULL;

